import './globals.css'
import type { Metadata } from 'next'
import { Inter, Barriecito } from 'next/font/google'
import NavBar from './NavBar'
import { Suspense } from 'react'
import Loading from './loading'
import AuthProvider from './auth/Provider'
import GoogleAnalyticsScript from './GoogleAnalyticsScript'
import local from 'next/font/local'

const inter = Inter({ subsets: ['latin'] })

const barriecito = Barriecito({
  subsets: ['latin'],
  weight: ['400']
})

const clouts = local({
  src: '../public/fonts/Clouts.ttf',
  variable: '--font-clouts'
})

export const metadata: Metadata = {
  title: 'Nigga website',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" data-theme="winter">
      <GoogleAnalyticsScript/>
      <body className={clouts.variable}>
        <AuthProvider>
          <NavBar/>
          <main className="p-5">
            <Suspense fallback={<Loading/>}>
              {children}
            </Suspense>
          </main>
        </AuthProvider>
      </body>
    </html>
  )
}
